feat(pipes): add a pipe `mergeArrayByKey`
easyops-cn/brick-next-pipes pull request #16
Opened 2020-12-11 08:15 UTC by whuhyw

2020-12-11 09:53 UTC, whuhyw commented
@weareoutman

2020-12-12 02:46 UTC, weareoutman requested changes
需要在 src/pipes/index.ts 导出。

2020-12-12 02:46 UTC, weareoutman commented on src/pipes/mergeArrayByKey.ts
> +  arr2: unknown[]
- 这里应该支持任意数量的数组；
- 另外 pipes 特点是第一个参赛是主数据，所以这里可以考虑把参数改为：
  1. `dataList: unknown[][]`
  2. `key: string`

2020-12-14 02:16 UTC, whuhyw commented on src/pipes/mergeArrayByKey.ts
> +  arr2: unknown[]
done

2020-12-14 02:52 UTC, weareoutman requested changes

2020-12-14 02:52 UTC, weareoutman commented on src/pipes/mergeArrayByKey.ts
> + * @param key
`@param - dataList`

2020-12-14 02:52 UTC, weareoutman commented on src/pipes/mergeArrayByKey.ts
> +    return Object.values(merge(keyBy(acc, key), keyBy(cur, key)));
`_.merge` 会进行递归的合并，符合预期吗？比如：

例如 lodash 官方的示例：

```js
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }]
};
 
_.merge(object, other);
// => { 'a': [{ 'b': 2, 'c': 3 }, { 'd': 4, 'e': 5 }] }
```

2020-12-14 03:05 UTC, whuhyw commented on src/pipes/mergeArrayByKey.ts
> +    return Object.values(merge(keyBy(acc, key), keyBy(cur, key)));
不符合预期，要修改下

2020-12-14 03:55 UTC, whuhyw commented on src/pipes/mergeArrayByKey.ts
> +    return Object.values(merge(keyBy(acc, key), keyBy(cur, key)));
done

2020-12-14 03:55 UTC, whuhyw commented on src/pipes/mergeArrayByKey.ts
> + * @param key
done

2020-12-14 03:58 UTC, whuhyw commented
![image](https://user-images.githubusercontent.com/12651781/102038959-8c9f3480-3e03-11eb-8408-4df04bbb486c.png)
api-extractor 一直跑不过，不知道为啥，应该是注释写错了，你看下？

2020-12-14 04:18 UTC, weareoutman commented
> ![image](https://user-images.githubusercontent.com/12651781/102038959-8c9f3480-3e03-11eb-8408-4df04bbb486c.png)
> 
> api-extractor 一直跑不过，不知道为啥，应该是注释写错了，你看下？

可能忘了写说明了，改变对外接口后，需要在 npm run build 后再执行一次 npm run build:docs:dev

2020-12-14 05:55 UTC, weareoutman approved these changes

2020-12-14 05:58 UTC, merged